.TH "Command" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Command \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBViewCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExecute\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Command::Execute (\fBRequest\fP $Request)\fC [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
