.TH "configuration/constants.php" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
configuration/constants.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBCLASS_PATH\fP getenv ( 'DOCUMENT_ROOT' ) \&. '/phpwebtk/'"
.br
.ti -1c
.RI "const \fBCONFIG_FILE\fP \fBCLASS_PATH\fP \&. 'configuration/phpwebtk\&.xml'"
.br
.ti -1c
.RI "const \fBSCHEMA_FILE\fP \fBCLASS_PATH\fP \&. 'configuration/phpwebtk\&.xsd'"
.br
.ti -1c
.RI "const \fBADODB_PERF_NO_RUN_SQL\fP 0"
.br
.ti -1c
.RI "const \fBSMARTY_DIR\fP \fBCLASS_PATH\fP \&. 'addons/smarty\-3\&.1\&.21/'"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "const ADODB_PERF_NO_RUN_SQL 0"
Disable the 'Run SQL' link for the web-based user interface for performance monitoring\&. 
.SS "const CLASS_PATH getenv ( 'DOCUMENT_ROOT' ) \&. '/phpwebtk/'"
The system path to the location of the PHP Web Toolkit class files\&. 
.SS "const CONFIG_FILE \fBCLASS_PATH\fP \&. 'configuration/phpwebtk\&.xml'"
The system path to the location of the configuration XML file\&. 
.SS "const SCHEMA_FILE \fBCLASS_PATH\fP \&. 'configuration/phpwebtk\&.xsd'"
The system path to the location of the configuration XML Schema file\&. 
.SS "const SMARTY_DIR \fBCLASS_PATH\fP \&. 'addons/smarty\-3\&.1\&.21/'"
The system path to the location of the Smarty class files\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
