.TH "testscripts/controllertest.php" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testscripts/controllertest.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$start\fP = microtime ( 1 )"
.br
.ti -1c
.RI "\fB$Client\fP = new \fBClient\fP ()"
.br
.ti -1c
.RI "\fB$stop\fP = microtime ( 1 )"
.br
.ti -1c
.RI "\fB$time\fP = $stop \- $start"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$\fBClient\fP = new \fBClient\fP ()"

.SS "$start = microtime ( 1 )"

.SS "$stop = microtime ( 1 )"

.SS "$time = $stop \- $start"

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
