.TH "Controller" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Controller \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProcessRequest\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Controller::ProcessRequest (\fBRequest\fP $Request)"
function ProcessRequest
.PP
This method initiates a session to preserve specific information across subsequent requests; adds or strips slashes from the HTTP GET or HTTP POST information; executes customized operations; and transfers the modified \fBRequest\fP object to the Dispatch method along with the name of the view to present to the end user\&.
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI\fBRequest\fP\fP \fBRequest\fP object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
