.TH "DaoFactory" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DaoFactory \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMysqlDaoFactory\fP, \fBMysqliDaoFactory\fP, \fBMysqltDaoFactory\fP, \fBPostgres7DaoFactory\fP, \fBPostgres8DaoFactory\fP, and \fBXmlDaoFactory\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBGetDaoFactory\fP ($driver)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static DaoFactory::GetDaoFactory ( $driver)\fC [static]\fP"
function GetDaoFactory
.PP
This method builds a Data Source Name (DSN) and invokes the appropriate DAO Factory with the DSN as a parameter\&.
.PP
public
.PP
\fBReturns:\fP
.RS 4
mixed object instance|FALSE 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
