.TH "testscripts/digesttest.php" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
testscripts/digesttest.php \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB$start\fP = microtime ( 1 )"
.br
.ti -1c
.RI "\fB$plaintext\fP = 'what do ya want for nothing?'"
.br
.ti -1c
.RI "\fB$Digest\fP = new \fBDigest\fP ()"
.br
.ti -1c
.RI "\fB$ciphertext\fP = $\fBDigest\fP\->GetDigest ( $plaintext )"
.br
.ti -1c
.RI "if(FALSE!==$\fBDigest\fP\->IsValidDigest($ciphertext, $plaintext)) \fBelse\fP"
.br
.ti -1c
.RI "\fB$stop\fP = microtime ( 1 )"
.br
.ti -1c
.RI "\fB$time\fP = $stop \- $start"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "$ciphertext = $\fBDigest\fP\->GetDigest ( $plaintext )"

.SS "$\fBDigest\fP = new \fBDigest\fP ()"

.SS "$plaintext = 'what do ya want for nothing?'"

.SS "$start = microtime ( 1 )"

.SS "$stop = microtime ( 1 )"

.SS "$time = $stop \- $start"

.SS "if (FALSE!==$\fBDigest\fP\->IsValidDigest($ciphertext, $plaintext)) else"
\fBInitial value:\fP
.PP
.nf
{
    print ('<br />Invalid Signature')
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
