.TH "Digest" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Digest \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP ()"
.br
.ti -1c
.RI "\fBGetDigest\fP ($plaintext)"
.br
.ti -1c
.RI "\fBIsValidDigest\fP ($ciphertext, $plaintext)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Digest::__construct ()"
function __construct
.PP
This method is executed when an object is instantiated from this class\&. Preprocessing can be done here before the object is put into service\&.
.PP
public 
.SH "Member Function Documentation"
.PP 
.SS "Digest::GetDigest ( $plaintext)"
function GetDigest
.PP
This method generates a salted or unsalted message digest\&.
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIplaintext\fP Plaintext 
.RE
.PP
\fBReturns:\fP
.RS 4
string Base64 encoded ciphertext 
.RE
.PP

.SS "Digest::IsValidDigest ( $ciphertext,  $plaintext)"
function IsValidDigest
.PP
This method validates a salted or unsalted message digest\&.
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIciphertext\fP Ciphertext 
.br
\fIplaintext\fP Plaintext 
.RE
.PP
\fBReturns:\fP
.RS 4
boolean TRUE|FALSE 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
