.TH "Invoker" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Invoker \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSetCommand\fP (\fBCommand\fP $\fBCommand\fP)"
.br
.ti -1c
.RI "\fBExecuteCommand\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "Invoker::ExecuteCommand (\fBRequest\fP $Request)"
function SetCommand
.PP
This method executes the command and returns the result to the receiver\&.
.PP
private 
.SS "Invoker::SetCommand (\fBCommand\fP $Command)"
function SetCommand
.PP
This method sets the command\&.
.PP
private 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
