.TH "KsesRequestHandler" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
KsesRequestHandler \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRequestHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBCharacterFormatTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBOutputTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBBlockTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBLinkTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBFrameTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBInputTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBListTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBImageTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBTableTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBStyleTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBMetaInformationTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBProgrammingTags\fP (Kses5 $Kses5)"
.br
.ti -1c
.RI "\fBHandleRequest\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Member Function Documentation"
.PP 
.SS "KsesRequestHandler::BasicTags (Kses5 $Kses5)"
function BasicTags
.PP
This method allows and/or disallows XHTML's basic tags\&.
.PP
public 
.SS "KsesRequestHandler::BlockTags (Kses5 $Kses5)"
function BlockTags
.PP
This method allows and/or disallows XHTML's block tags\&.
.PP
public 
.SS "KsesRequestHandler::CharacterFormatTags (Kses5 $Kses5)"
function CharacterFormatTags
.PP
This method allows and/or disallows XHTML's character format tags\&.
.PP
public 
.SS "KsesRequestHandler::FrameTags (Kses5 $Kses5)"
function FrameTags
.PP
This method allows and/or disallows XHTML's frame tags\&.
.PP
public 
.SS "KsesRequestHandler::HandleRequest (\fBRequest\fP $Request)"
function HandleRequest
.PP
This method processes the request if certain conditions are met\&.
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fI\fBRequest\fP\fP \fBRequest\fP object 
.RE
.PP

.SS "KsesRequestHandler::ImageTags (Kses5 $Kses5)"
function ImageTags
.PP
This method allows and/or disallows XHTML's image tags\&.
.PP
public 
.SS "KsesRequestHandler::InputTags (Kses5 $Kses5)"
function InputTags
.PP
This method allows and/or disallows XHTML's input tags\&.
.PP
public 
.SS "KsesRequestHandler::LinkTags (Kses5 $Kses5)"
function LinkTags
.PP
This method allows and/or disallows XHTML's link tags\&.
.PP
public 
.SS "KsesRequestHandler::ListTags (Kses5 $Kses5)"
function ListTags
.PP
This method allows and/or disallows XHTML's list tags\&.
.PP
public 
.SS "KsesRequestHandler::MetaInformationTags (Kses5 $Kses5)"
function MetaInformationTags
.PP
This method allows and/or disallows XHTML's meta information tags\&.
.PP
public 
.SS "KsesRequestHandler::OutputTags (Kses5 $Kses5)"
function OutputTags
.PP
This method allows and/or disallows XHTML's output tags\&.
.PP
public 
.SS "KsesRequestHandler::ProgrammingTags (Kses5 $Kses5)"
function ProgrammingTags
.PP
This method allows and/or disallows XHTML's programming tags\&.
.PP
public 
.SS "KsesRequestHandler::StyleTags (Kses5 $Kses5)"
function StyleTags
.PP
This method allows and/or disallows XHTML's style tags\&.
.PP
public 
.SS "KsesRequestHandler::TableTags (Kses5 $Kses5)"
function TableTags
.PP
This method allows and/or disallows XHTML's table tags\&.
.PP
public 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
