.TH "PException" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
PException \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits Exception\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBDisplay\fP (Exception $Exception)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static PException::Display (Exception $Exception)\fC [static]\fP"
function Display
.PP
This method formats the error message appropriately and displays it\&.
.PP
public 
.PP
\fBParameters:\fP
.RS 4
\fIException\fP Exception object 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
