.TH "RequestBuilder" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequestBuilder \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBHttpRequestBuilder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBuildHttpAccept\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpAcceptCharset\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpAcceptEncoding\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpAcceptLanguage\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpConnection\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpGet\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpHost\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpPost\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpReferer\fP ()"
.br
.ti -1c
.RI "\fBBuildHttpUserAgent\fP ()"
.br
.ti -1c
.RI "\fBBuildQueryString\fP ()"
.br
.ti -1c
.RI "\fBBuildRemoteAddress\fP ()"
.br
.ti -1c
.RI "\fBBuildRemoteHost\fP ()"
.br
.ti -1c
.RI "\fBBuildRemotePort\fP ()"
.br
.ti -1c
.RI "\fBBuildRemoteProxyAddr\fP ()"
.br
.ti -1c
.RI "\fBBuildRemoteProxyHost\fP ()"
.br
.ti -1c
.RI "\fBBuildRequestMethod\fP ()"
.br
.ti -1c
.RI "\fBBuildRequestUri\fP ()"
.br
.ti -1c
.RI "\fBBuildServerProtocol\fP ()"
.br
.ti -1c
.RI "\fBGetRequest\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "RequestBuilder::BuildHttpAccept ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpAcceptCharset ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpAcceptEncoding ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpAcceptLanguage ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpConnection ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpGet ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpHost ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpPost ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpReferer ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildHttpUserAgent ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildQueryString ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRemoteAddress ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRemoteHost ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRemotePort ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRemoteProxyAddr ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRemoteProxyHost ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRequestMethod ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildRequestUri ()\fC [abstract]\fP"

.SS "RequestBuilder::BuildServerProtocol ()\fC [abstract]\fP"

.SS "RequestBuilder::GetRequest ()\fC [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
