.TH "RequestDirector" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RequestDirector \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstructRequest\fP (\fBRequestBuilder\fP $\fBRequestBuilder\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "RequestDirector::ConstructRequest (\fBRequestBuilder\fP $RequestBuilder)"
function ConstructRequest
.PP
This method assembles the specified parts (below) of the \fBRequest\fP\&.
.PP
public 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
