.TH "SampleView" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleView \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisplay\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SampleView::__construct (\fBRequest\fP $Request)"
function __construct
.PP
This method is executed when an object is instantiated from this class\&. Preprocessing can be done here before the object is put into service\&.
.PP
public 
.SH "Member Function Documentation"
.PP 
.SS "SampleView::Display ()\fC [static]\fP"
function Display
.PP
This method displays the complete view to the user\&.
.PP
public 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
