.TH "SampleDao" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SampleDao \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBMysqliSampleDao\fP, \fBMysqlSampleDao\fP, and \fBMysqltSampleDao\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInsertSample\fP ()"
.br
.ti -1c
.RI "\fBDeleteSample\fP ()"
.br
.ti -1c
.RI "\fBFindSample\fP ()"
.br
.ti -1c
.RI "\fBUpdateSample\fP ()"
.br
.ti -1c
.RI "\fBSelectSampleRS\fP ()"
.br
.ti -1c
.RI "\fBSelectSampleTO\fP ()"
.br
.ti -1c
.RI "\fBGetData\fP ($RecordSet)"
.br
.ti -1c
.RI "\fBGetDataTO\fP ($RecordSet)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "SampleDao::DeleteSample ()\fC [abstract]\fP"

.SS "SampleDao::FindSample ()\fC [abstract]\fP"

.SS "SampleDao::GetData ( $RecordSet)\fC [abstract]\fP"

.SS "SampleDao::GetDataTO ( $RecordSet)\fC [abstract]\fP"

.SS "SampleDao::InsertSample ()\fC [abstract]\fP"

.SS "SampleDao::SelectSampleRS ()\fC [abstract]\fP"

.SS "SampleDao::SelectSampleTO ()\fC [abstract]\fP"

.SS "SampleDao::UpdateSample ()\fC [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
