.TH "View" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
View \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAction\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "View::Action (\fBRequest\fP $Request)"
function Action
.PP
This method defines the operation(s) to be executed by the invoker\&.
.PP
private 

.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
