.TH "ViewCommand" 3 "Sat Nov 12 2016" "PHP Web Toolkit 1.0.4 Alpha (phpwebtk)" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ViewCommand \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCommand\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB__construct\fP (\fBView\fP $Receiver)"
.br
.ti -1c
.RI "\fBExecute\fP (\fBRequest\fP $\fBRequest\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fB$Receiver\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ViewCommand::__construct (\fBView\fP $Receiver)"
function __construct
.PP
This method is executed when an object is instantiated from this class\&. Preprocessing can be done here before the object is put into service\&.
.PP
private 
.SH "Member Function Documentation"
.PP 
.SS "ViewCommand::Execute (\fBRequest\fP $Request)"
function Execute
.PP
This method executes the action and returns the result to the invoker\&.
.PP
public 
.SH "Member Data Documentation"
.PP 
.SS "ViewCommand::$Receiver\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PHP Web Toolkit 1\&.0\&.4 Alpha (phpwebtk) from the source code\&.
